# Generated by Django 4.0.6 on 2022-08-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_age_user_expense_user_expense_body_user_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='party_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='written',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
