# Generated by Django 4.0.6 on 2022-08-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_party_num_user_written_delete_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='party_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='written',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
