# Generated by Django 4.0.6 on 2022-08-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default.png', null=True, upload_to=''),
        ),
    ]
