# Generated by Django 4.0.6 on 2022-08-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('teammate_cnt', models.IntegerField()),
                ('team1_no', models.IntegerField(null=True)),
                ('team2_no', models.IntegerField(null=True)),
                ('team3_no', models.IntegerField(null=True)),
                ('team4_no', models.IntegerField(null=True)),
                ('leader_no', models.IntegerField(null=True)),
                ('content', models.TextField()),
                ('p_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
