# Generated by Django 4.0.6 on 2022-08-20 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.AutoField(primary_key=True, serialize=False)),
                ('team_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('team_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('leader_no', models.ForeignKey(db_column='leader_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_bad_users', models.ManyToManyField(blank=True, related_name='team_bad_user', to=settings.AUTH_USER_MODEL)),
                ('team_good_users', models.ManyToManyField(blank=True, related_name='team_good_user', to=settings.AUTH_USER_MODEL)),
                ('team_users', models.ManyToManyField(blank=True, related_name='team_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-team_date'],
            },
        ),
        migrations.CreateModel(
            name='Team_Board',
            fields=[
                ('team_board_no', models.AutoField(primary_key=True, serialize=False)),
                ('team_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_body', models.TextField()),
                ('team_no', models.ForeignKey(db_column='team_no', on_delete=django.db.models.deletion.CASCADE, to='party.team')),
                ('team_writer_no', models.ForeignKey(db_column='team_user_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-team_date'],
            },
        ),
        migrations.CreateModel(
            name='Team_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_use_date', models.CharField(max_length=40)),
                ('team_cost', models.IntegerField()),
                ('team_place', models.CharField(max_length=100)),
                ('team_body', models.TextField()),
                ('team_board_no', models.ForeignKey(db_column='team_board_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team_board')),
                ('team_no', models.ForeignKey(db_column='team_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team')),
                ('team_user_no', models.ForeignKey(db_column='team_user_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_body', models.TextField()),
                ('team_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_no', models.ForeignKey(db_column='team_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team')),
                ('team_user_no', models.ForeignKey(db_column='team_user_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
