# Generated by Django 4.0.6 on 2022-08-04 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Board',
            fields=[
                ('Team_board_no', models.AutoField(primary_key=True, serialize=False)),
                ('Team_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Team_body', models.TextField()),
                ('Team_good_cnt', models.IntegerField(default=0)),
                ('Team_bad_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Team_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_use_date', models.DateTimeField()),
                ('Team_cost', models.IntegerField()),
                ('Team_place', models.CharField(max_length=100)),
                ('Team_body', models.TextField()),
                ('Team_board_no', models.ForeignKey(db_column='Team_board_no', on_delete=django.db.models.deletion.CASCADE, to='party.team_board')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_body', models.TextField()),
                ('Team_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Team_board_no', models.ForeignKey(db_column='Team_board_no', on_delete=django.db.models.deletion.CASCADE, to='party.team_board')),
            ],
        ),
        migrations.AddField(
            model_name='team_board',
            name='team_no',
            field=models.ForeignKey(db_column='team_no', on_delete=django.db.models.deletion.CASCADE, to='party.team'),
        ),
    ]
