# Generated by Django 4.0.6 on 2022-08-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_team_board_alter_team_team_name_team_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team1_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team2_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team3_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team4_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teammate_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
