# Generated by Django 4.0.6 on 2022-08-12 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0003_alter_team_category_alter_team_leader_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_board',
            options={'ordering': ['-team_date']},
        ),
        migrations.RenameField(
            model_name='team_board',
            old_name='Team_board_no',
            new_name='team_board_no',
        ),
        migrations.RenameField(
            model_name='team_board',
            old_name='Team_body',
            new_name='team_body',
        ),
        migrations.RenameField(
            model_name='team_board',
            old_name='Team_date',
            new_name='team_date',
        ),
        migrations.RenameField(
            model_name='team_comment',
            old_name='Team_body',
            new_name='team_body',
        ),
        migrations.RenameField(
            model_name='team_comment',
            old_name='Team_date',
            new_name='team_date',
        ),
        migrations.RenameField(
            model_name='team_receipt',
            old_name='Team_body',
            new_name='team_body',
        ),
        migrations.RenameField(
            model_name='team_receipt',
            old_name='Team_cost',
            new_name='team_cost',
        ),
        migrations.RenameField(
            model_name='team_receipt',
            old_name='Team_place',
            new_name='team_place',
        ),
        migrations.RenameField(
            model_name='team_receipt',
            old_name='Team_use_date',
            new_name='team_use_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='p_user_no',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team1_no',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team2_no',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team3_no',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team4_no',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teammate_cnt',
        ),
        migrations.RemoveField(
            model_name='team_board',
            name='Team_bad_cnt',
        ),
        migrations.RemoveField(
            model_name='team_board',
            name='Team_good_cnt',
        ),
        migrations.RemoveField(
            model_name='team_comment',
            name='Team_board_no',
        ),
        migrations.RemoveField(
            model_name='team_receipt',
            name='Team_board_no',
        ),
        migrations.AddField(
            model_name='team',
            name='team_users',
            field=models.ManyToManyField(related_name='team_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_board',
            name='team_bad_users',
            field=models.ManyToManyField(blank=True, related_name='team_bad_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_board',
            name='team_good_users',
            field=models.ManyToManyField(blank=True, related_name='team_good_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_board',
            name='team_user_no',
            field=models.ForeignKey(db_column='team_user_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_comment',
            name='team_board_no',
            field=models.ForeignKey(db_column='team_board_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team_board'),
        ),
        migrations.AddField(
            model_name='team_comment',
            name='team_user_no',
            field=models.ForeignKey(db_column='team_user_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team_receipt',
            name='team_board_no',
            field=models.ForeignKey(db_column='team_board_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team_board'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader_no',
            field=models.ForeignKey(db_column='leader_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
