# Generated by Django 4.0.6 on 2022-08-13 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0005_alter_team_options_team_team_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_users',
            field=models.ManyToManyField(blank=True, related_name='team_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
