# Generated by Django 4.0.6 on 2022-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_alter_team_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_receipt',
            name='team_use_date',
            field=models.CharField(max_length=40),
        ),
    ]
