# Generated by Django 4.0.6 on 2022-08-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_alter_team_receipt_team_use_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_board',
            name='team_user_no',
        ),
    ]
