# Generated by Django 4.0.6 on 2022-08-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0008_remove_team_board_team_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_board',
            name='team_writer_no',
            field=models.ForeignKey(db_column='team_user_no', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
