# Generated by Django 4.0.6 on 2022-08-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_team_receipt_team_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_receipt',
            name='team_no',
            field=models.ForeignKey(db_column='team_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team'),
        ),
    ]
