# Generated by Django 4.0.6 on 2022-08-14 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0011_team_receipt_team_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_comment',
            name='team_board_no',
        ),
        migrations.AddField(
            model_name='team_comment',
            name='team_no',
            field=models.ForeignKey(db_column='team_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='party.team'),
        ),
    ]
