# Generated by Django 4.0.6 on 2022-08-18 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0012_remove_team_comment_team_board_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_board',
            name='team_bad_users',
        ),
        migrations.RemoveField(
            model_name='team_board',
            name='team_good_users',
        ),
        migrations.AddField(
            model_name='team',
            name='team_bad_users',
            field=models.ManyToManyField(blank=True, related_name='team_bad_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_good_users',
            field=models.ManyToManyField(blank=True, related_name='team_good_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
