# Generated by Django 4.0.6 on 2022-08-04 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('good_cnt', models.IntegerField(default=0)),
                ('bad_cnt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_date', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('board_no', models.ForeignKey(db_column='board_no', on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('board_no', models.ForeignKey(db_column='board_no', on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(null=True, to='board.tag'),
        ),
        migrations.AddField(
            model_name='board',
            name='user_no',
            field=models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
