# Generated by Django 4.0.6 on 2022-08-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(blank=True, to='board.tag'),
        ),
    ]
