# Generated by Django 4.0.6 on 2022-08-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-date']},
        ),
    ]
