# Generated by Django 4.0.6 on 2022-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='board.tag'),
        ),
    ]
