# Generated by Django 4.0.6 on 2022-08-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-date']},
        ),
    ]
