# Generated by Django 4.0.6 on 2022-08-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='board.tag')),
            ],
        ),
    ]
