# Generated by Django 4.0.6 on 2022-08-09 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_delete_boardtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 9, 16, 6, 36, 403684, tzinfo=utc)),
        ),
    ]
