# Generated by Django 4.0.6 on 2022-08-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_comment_date_alter_receipt_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='use_date',
            field=models.CharField(max_length=50),
        ),
    ]
