# Generated by Django 4.0.6 on 2022-08-11 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_alter_receipt_use_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='bad_cnt',
        ),
        migrations.RemoveField(
            model_name='board',
            name='good_cnt',
        ),
        migrations.AddField(
            model_name='board',
            name='bad_user',
            field=models.ManyToManyField(blank=True, related_name='bad_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='good_user',
            field=models.ManyToManyField(blank=True, related_name='good_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
