# Generated by Django 4.0.6 on 2022-08-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Board',
            fields=[
                ('M_board_no', models.AutoField(primary_key=True, serialize=False)),
                ('M_title', models.CharField(max_length=40)),
                ('M_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('M_body', models.TextField()),
                ('M_good_cnt', models.IntegerField(default=0)),
                ('M_bad_cnt', models.IntegerField(default=0)),
                ('M_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='M_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_use_date', models.DateTimeField()),
                ('M_cost', models.IntegerField()),
                ('M_place', models.CharField(max_length=100)),
                ('M_body', models.TextField()),
                ('M_board_no', models.ForeignKey(db_column='M_board_no', on_delete=django.db.models.deletion.CASCADE, to='board_monthly.m_board')),
                ('M_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='M_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_body', models.TextField()),
                ('M_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('M_board_no', models.ForeignKey(db_column='M_board_no', on_delete=django.db.models.deletion.CASCADE, to='board_monthly.m_board')),
                ('M_name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
