# Generated by Django 4.0.6 on 2022-08-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_no', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('teammate_cnt', models.IntegerField()),
                ('teammate_limit', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
