# Generated by Django 4.0.6 on 2022-08-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='W_Board',
            fields=[
                ('W_board_no', models.AutoField(primary_key=True, serialize=False)),
                ('W_title', models.CharField(max_length=40)),
                ('W_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('W_body', models.TextField()),
                ('W_good_cnt', models.IntegerField(default=0)),
                ('W_bad_cnt', models.IntegerField(default=0)),
                ('W_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='W_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_use_date', models.DateTimeField()),
                ('W_cost', models.IntegerField()),
                ('W_place', models.CharField(max_length=100)),
                ('W_body', models.TextField()),
                ('W_board_no', models.ForeignKey(db_column='W_board_no', on_delete=django.db.models.deletion.CASCADE, to='board_weekly.w_board')),
                ('W_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='W_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_body', models.TextField()),
                ('W_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('W_board_no', models.ForeignKey(db_column='W_board_no', on_delete=django.db.models.deletion.CASCADE, to='board_weekly.w_board')),
                ('W_name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
