# Generated by Django 4.0.6 on 2022-08-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Board',
            fields=[
                ('D_board_no', models.AutoField(primary_key=True, serialize=False)),
                ('D_title', models.CharField(max_length=40)),
                ('D_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('D_body', models.TextField()),
                ('D_good_cnt', models.IntegerField(default=0)),
                ('D_bad_cnt', models.IntegerField(default=0)),
                ('D_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='D_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_use_date', models.DateTimeField()),
                ('D_cost', models.IntegerField()),
                ('D_place', models.CharField(max_length=100)),
                ('D_body', models.TextField()),
                ('D_board_no', models.ForeignKey(db_column='D_board_no', on_delete=django.db.models.deletion.CASCADE, to='board_daily.d_board')),
                ('D_user_no', models.ForeignKey(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='D_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_body', models.TextField()),
                ('D_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('D_board_no', models.ForeignKey(db_column='D_board_no', on_delete=django.db.models.deletion.CASCADE, to='board_daily.d_board')),
                ('D_name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
